name: "Histoire de la Cryptographie"
description: "Ce site Internet a été réalisé en 2018 par Manon Pathier, Hugo Medori et Samuel Gallay, élèves au Lycée du Grésivaudan à Meylan en classe de première scientifique dans le cadre de leur TPE."
