name: "Histoire de la Cryptographie"
description: "Ce site Internet a été réalisé en 2018 par Samuel Gallay, Hugo Medori et Manon Pathier, élèves au Lycée du Grésivaudan de Meylan en première scientifique dans le cadre de leur TPE."
