name: "Histoire de la Cryptographie"
description: "Ce site Internet a été réalisé en 2018 par Samuel Gallay, Hugo Medori et Manon Pathier, élèves au Lycée du Grésivaudan à Meylan en classe de première scientifique dans le cadre de leur TPE."
